"""remove_content_field_from_lecture

Revision ID: 74f372186050
Revises: 9c14dea4bef2
Create Date: 2025-02-13 01:55:53.481129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f372186050'
down_revision = '9c14dea4bef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('video_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.create_foreign_key('fk_lecture_subject', 'subject', ['subject_id'], ['id'])
        batch_op.drop_column('content')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('lecture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('fk_quiz_lecture', type_='foreignkey')
        batch_op.create_foreign_key('fk_quiz_lecture_new', 'lecture', ['lecture_id'], ['id'])
        batch_op.drop_column('source_lecture_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_lecture_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_quiz_lecture_new', type_='foreignkey')
        batch_op.create_foreign_key('fk_quiz_lecture', 'lecture', ['source_lecture_id'], ['id'])
        batch_op.alter_column('lecture_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('lecture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.drop_constraint('fk_lecture_subject', type_='foreignkey')
        batch_op.alter_column('video_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
